# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-amplify
  description: This component is responsible for provisioning AWS Amplify apps, backend environments, branches, domain associations, and webhooks
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component







